env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
overrides: []
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
rules: {}
